---
title: "Week 5 Problem Based Learning and Practical Solutions"
author: |
  | Jeffrey O. Hanson$^1$
  | $^1$School of Biological Sciences, The University of Queensland, Brisbane, QLD, Australia
  | Correspondance should be addressed to jeffrey.hanson@uqconnect.edu.au
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::pdf_document:
    toc: true
    toc_depth: 5
    keep_tex: no
    includes:
      in_header: preamble-latex.tex
fontsize: 11pt
documentclass: article
bibliography: ref_lib.bib
csl: reference-style.csl
---

## Problem based learning workshop
### General notes
* Main emphasis
+ Fixed/random
+ nested/crossed
* **Make them draw a diagram for each answer**

### Experiment 1
Two levels of salinity, and two diets are to be applied to a fish species to determine how these treatments affect the level of a hormone. There are 12 tanks for you to use. Design the experiment (draw it), and write down whether the factors in your design are fixed or random, and how your factors relate to each other.

|          | Diet 1 |  Diet 2  |
|:--------:|:------:|:--------:|
Salinity 1 | 3 tanks| 3 tanks  |
Salinity 2 | 3 tanks| 3 tanks  |

* Multiple fish are in each tank.
* Diet and salinity are crossed and both fixed factors.
* Tank is nested within diet and salinity.
* Tank is a random factor.

### Experiment 2
Eight different genetic strains of housefly were tested for their resistance to DDT. Each strain was raised in three bottles and eight females flies weer tested from each bottle.
1. Define whether strain and bottle are fixed or random, and whether the two factors are crossed or nested.

* Eight separate strains.
* Three bottle for each strain
* Bottle 1 for strain 1 has different flies to bottle 1 for strain 2.
* Bottle is nested within strain.

* Strain could be fixed if we are interested in differences between strain. Or, it could be random--it depends on the question.
* Bottle is random

2. In the ANOVA table below,  identify the numerator and the denominator for the F ratio of 8.47 for the strain term and state why this denominator is used rather than another.

* The numerator for the F ratio is the MSQ for "among bottles within strain" and the denominator is the degrees of freedom ($df$). Why is this the numerator? We've told the analysis that bottle is a random factor. So that's our unit of replication. If we used the "within bottle" MSQ and $df$ then we would assume that each fly is independent. The reason why the $df$ is 16 is because we do (number of strains $\times$ number of bottles per strain) -  number of bottles.

### Experiment 3
You have 50 inbred strains of mice, and each strain each strain has been typed for a molecular marker at the locus "Einsten"; 25 lines are found to be homozygous for the A allele, and 25 lines have the B allele. Design an experiment to test whether the "Einstein" locus affects intelligence in mice, and indicate what analysis you would use.

* We have AA with 25 lines, and we have BB with 25 lines.
* First, we need to design a metric that is easily measurable. Perhaps we might make them solve a maze?
* Analysis the data using an ANOVA.
* Genotype is a fixed effect (AA vs. BB)
* Line is nested within genotype and random. This is because line 1 for AA has different mice compared to line 1 for BB.

## \texttt{R} practical session
### General notes




