---
title: "Week 1 Problem Based Learning and Practical Solutions"
author: |
  | Jeffrey O. Hanson$^1$
  | $^1$School of Biological Sciences, The University of Queensland, Brisbane, QLD, Australia
  | Correspondance should be addressed to jeffrey.hanson@uqconnect.edu.au
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmarkdown::pdf_document:
    toc: true
    toc_depth: 5
    keep_tex: no
    includes:
      in_header: preamble-latex.tex
fontsize: 11pt
documentclass: article
bibliography: ref_lib.bib
csl: reference-style.csl
---

## Problem based learning workshop


## \texttt{R} practical session
### General notes on using the teaching manual 
* network information
* always use Windows 7
	+ Map to L drive: `\\\\sci-tl01.soe.uq.edu.au\\Teaching\\BIOL\\BIOL2006`
	+ Program name: `BIOL2006PracManual_2016.exe`
* sign on
	+ must enter valid id
	+ my sign on is `"Jeffrey"`
* GUI
	+ popup links are bright green
	+ arrows to navigate
	+ home icon is home
	+ R icon saves code to desktop and open up with Rstudio
	+ R code is in blue
	+ comments in black
	+ questions also in green
	+ tooltips appear in brown bar along the bottom of program
	+ minimize question popups by clicking on question again
	+ assessment questions turn black after they're done, but note that you might have to mouse over questions for them to turn black due to bug
	+ students must click logout to store results, they cannot just close the program
	+ students must answer all practice questions to get to final assessment questions
	+ each question in the assessment page refers to a specific page with info on how to answer it
* R scripts
	+ right click on the scripts
	+ open with -> Rstudio
* Potential issues
	* the computers don't associate .R scripts with Rstudio: need to open Rstudio first then open the script
	* attaching datasets: **never to do this even though it looks handy**
	
